spring:
  application:
    name: RequestService
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432}/${DATABASE_NAME:requestdb}?currentSchema=${DATABASE_SCHEMA:public}
    username: ${SPRING_DATASOURCE_USERNAME:azimusma}
    password: ${SPRING_DATASOURCE_PASSWORD:azimusma}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  mail:
    host: "smtp.timeweb.ru"
    port: 2525
    username: "astu@ttraum.ru"
    password: "eoaABoK=L3t<x>"
    email: "astu@ttraum.ru"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
service:
  host: ${ACCOUNT_HOST:http://localhost:8080/}

server:
  tomcat:
    keep-alive-timeout: 60000